spring:
h2:
  console.enabled: true
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  generate-ddl: true
datasource:
  url: ${DATABASE_URL:jdbc:h2:mem:docker}
  username: ${DATABASE_USERNAME:sa}
  password: ${DATABASE_PASSWORD:password}
  base-package: com.example.demoSpring3.repositories
server:
  error:
    include-messages: always
  port: 8081
